#!/usr/bin/env bash
while true
do
    export DISPLAY=:0.0
    battery_percent=$(acpi -b | grep -P -o '[0-9]+(?=%)')
    if on_ac_power; then
        if [ "$battery_percent" -gt 95 ]; then
            notify-send -i "Battery full." "Level: ${battery_percent}% "
            mpv /usr/share/sounds/ubuntu/ringtones/Alarm\ clock.ogg
        fi
    fi
    sleep 30 # (30 seconds)
done

# Notes: apt install acpi powermgmt-base
